version: '3'
services:
  web:
    build: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=your_app_key
      - DB_CONNECTION=pgsql
      - DB_HOST=your_db_host
      - DB_PORT=5432
      - DB_DATABASE=your_db_name
      - DB_USERNAME=your_db_username
      - DB_PASSWORD=your_db_password
      - MAIL_MAILER=smtp
      - MAIL_HOST=your_smtp_host
      - MAIL_PORT=587
      - MAIL_USERNAME=your_smtp_username
      - MAIL_PASSWORD=your_smtp_password
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME="${APP_NAME}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_db_username
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
